name: Generate Sitemap

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Sitemap
        uses: devops-infra/action-sitemap@v1
        with:
          base-url: 'https://muammeraslan0304-rgb.github.io/Modmen-_key_sat-/'
          output-file: 'sitemap.xml'

      - name: Commit and Push Sitemap
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add sitemap.xml
          git commit -m "Update sitemap"
          git push
